# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    name: Build & Test
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        workDir: [./front-end]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4

    - name: Cache node modules
      uses: actions/cache@v4
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
          
    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        
    - name: Install Dependencies
      working-directory: ${{ matrix.workDir }}
      run: npm install
          
    - name: Clean Distribution Directory
      working-directory: ${{ matrix.workDir }}
      run: npm run ci:clean

    - name: Build Application
      working-directory: ${{ matrix.workDir }}
      run: npm run ci:build

    - name: Run Unit Tests
      working-directory: ${{ matrix.workDir }}
      run: npm run ci:test

    - name: List Files in Distribution Directory
      working-directory: ${{ matrix.workDir }}
      run: ls -R ./dist
