name: "Labeling new issue"
on:
  issues:
    types: ['opened', 'edited']

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: Renato66/auto-label@v3.1.1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          labels-not-allowed: '["Stale","Pendente de informações","Falta de informações"]'